version: '3'

services:

  web-server:
    build:
      context: ./web
    ports:
      - 80:6000 # host : container
    env_file:
      ./credentials.env
    volumes:
      - ./web/src:/app
    container_name: agile-web

  db-server:
    image: mysql:latest
    restart: always
    env_file:
      ./credentials.env
    ports:
      - 3306:3306 # host : container
    command: --init-file /init_db.sql
    volumes:
      - ./database/init_db.sql:/init_db.sql
      - ./database/persistent_db:/var/lib/mysql # persistent DB when container is stopped
    container_name: agile-db

volumes:
  persistent_db:
